import Container from "@/components/layout/Container";
import Section from "@/components/layout/Section";
import CTASection from "@/components/marketing/CTASection";
import FeatureGrid from "@/components/marketing/FeatureGrid";
import ProductHero from "@/components/marketing/ProductHero";
import SectionIntro from "@/components/marketing/SectionIntro";
import { buildPageMetadata } from "@/lib/metadata";

export const metadata = buildPageMetadata({
  title: "Copilot Voice Intelligence",
  description:
    "Copilot Voice Intelligence delivers voice-narrated deterministic intelligence for executives, analysts, and architects working with governed runtime security workflows.",
  path: "/products/copilot-voice-intelligence",
});

const modes = [
  {
    title: "Executive Mode",
    body:
      "High-level summaries, impact framing, and decision-ready narration for leadership and governance stakeholders.",
  },
  {
    title: "Analyst Mode",
    body:
      "Security-oriented explanation with context around severity, attack path, control gaps, and guided investigation.",
  },
  {
    title: "Academy Mode",
    body:
      "Guided explanation designed to teach first-principles cloud and runtime security concepts through narrated walkthroughs.",
  },
] as const;

const useCases = [
  {
    title: "Executive review and risk communication",
    body:
      "Narrated posture summaries and governance context for decision-makers who need fast clarity without losing technical grounding.",
  },
  {
    title: "Analyst explanation during investigation",
    body:
      "Deterministic records, risk context, and runtime events translated into guided operational explanation.",
  },
  {
    title: "Architecture walkthroughs and system briefings",
    body:
      "Explain platform flows, trust boundaries, and runtime control paths in a format suited for technical reviews.",
  },
  {
    title: "Training and guided learning",
    body:
      "Use narrated walkthroughs to teach governed security operations without weakening the truth model underneath.",
  },
] as const;

export default function CopilotVoiceIntelligencePage() {
  return (
    <>
      <ProductHero
        eyebrow="OPERATIONAL INTELLIGENCE"
        headline="Copilot Voice Intelligence: Narrated Intelligence Grounded in Deterministic Truth"
        subheadline="Copilot Voice Intelligence interprets deterministic SecureTheCloud records and runtime context to deliver narrated security posture, attack-path explanation, and architecture guidance for executives, analysts, and architects."
        primaryCta={{ label: "Open Copilot", href: "/request-demo" }}
        secondaryCta={{ label: "Try Voice Mode", href: "/request-demo" }}
      />

      <Section>
        <Container>
          <SectionIntro
            eyebrow="WHAT IT IS"
            title="A Voice Interface for Governed Security Intelligence"
            body="Copilot Voice Intelligence is not a generic chatbot. It is a voice and narration layer designed to explain anchored runtime truth. It helps teams interpret deterministic decision records, risk context, attack-path insights, and architectural posture in a more accessible operational format."
          />
        </Container>
      </Section>

      <Section className="border-y border-white/10 bg-white/[0.02]">
        <Container>
          <SectionIntro
            eyebrow="MODES"
            title="Built for Multiple Operating Contexts"
            body="Copilot Voice Intelligence is designed to support leadership, analysts, and learning workflows without disconnecting the explanation layer from deterministic runtime facts."
          />
          <div className="mt-10">
            <FeatureGrid items={modes} />
          </div>
        </Container>
      </Section>

      <Section>
        <Container>
          <SectionIntro
            eyebrow="DETERMINISTIC PRINCIPLE"
            title="Copilot Explains Anchored Facts — It Does Not Invent Them"
            body="Copilot Voice Intelligence is designed to interpret deterministic runtime facts generated by SecureTheCloud. Decisions remain explainable even if the voice layer is unavailable, because the underlying decision path, reason codes, and governance records remain intact."
          />
          <p className="mt-8 text-2xl font-semibold tracking-tight text-white sm:text-3xl">
            If Copilot is offline, the deterministic record still explains the decision.
          </p>
        </Container>
      </Section>

      <Section className="border-y border-white/10 bg-white/[0.02]">
        <Container>
          <SectionIntro
            eyebrow="VOICE EXPERIENCE"
            title="Narration for Security Posture, Attack Paths, and Architecture"
            body="Use Copilot Voice Intelligence to hear runtime posture, blast-radius implications, governance decisions, and system architecture summarized in real time. The experience is designed for teams who need clearer operational understanding without giving up control over accuracy."
          />
        </Container>
      </Section>

      <Section>
        <Container>
          <SectionIntro
            eyebrow="USE CASES"
            title="Where Voice Intelligence Adds Operational Value"
            body="Voice narration is most valuable when teams need faster operational understanding without replacing the deterministic truth model behind SecureTheCloud."
          />
          <div className="mt-10">
            <FeatureGrid items={useCases} />
          </div>
        </Container>
      </Section>

      <Section className="border-y border-white/10 bg-white/[0.02]">
        <Container>
          <SectionIntro
            eyebrow="CLOSING"
            title="Voice-Narrated Intelligence for Governed Security Workflows"
            body="Copilot Voice Intelligence makes deterministic SecureTheCloud context easier to interpret across technical and executive audiences without weakening the truth model underneath."
          />
        </Container>
      </Section>

      <CTASection
        headline="Hear deterministic intelligence in action."
        subheadline="See how Copilot Voice Intelligence turns runtime facts, decision records, and architecture context into narrated operational understanding."
        primaryCta={{ label: "Open Copilot", href: "/request-demo" }}
        secondaryCta={{ label: "Try Voice Mode", href: "/request-demo" }}
      />
    </>
  );
}
